<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="../RDdzJRHnBLCEdVSLXLrGQGpDR4VqvugXDfhZQLeH7rBPaktPjdyNesqcSztt/mvdMfMJ4nhXj5vh8pd8AgqPf3d2fgTZsRkHTm6AJGpvVd7bX7ffRjpM9Y3uX/2uPMGEnqMGu7ybFSH7PxKaT5bw7Tnx76UkaaadeYV7A2Kx5sPp8pks4DAXDK3.png" usemap="#image-map">

<map name="image-map">
    <area target="" alt="Falso" title="Falso" href="/trivia/ch5U7hVmGLftf2yAQNwn5UYxA8e2wAXQbqNtfqtfDCX9YChujNutWztmRx4s6/" coords="270,1398,270,1465,350,1466,376,1529,434,1577,501,1607,583,1589,652,1546,691,1469,772,1468,772,1396,687,1373,659,1314,597,1267,530,1250,457,1261,387,1312,346,1396" shape="poly">
    <area target="" alt="Verdadero" title="Verdadero" href="/trivia/cUpy2mWPdwqBp5bWjgWVuP4EvzaAabE37tuuKnTEYtFMmxj6ynuYApLvwyF4V/" coords="270,946,270,1017,350,1015,385,1081,411,1114,488,1146,572,1141,642,1099,682,1048,689,1013,771,1014,769,944,687,921,658,858,593,812,519,795,433,817,377,867,349,942" shape="poly">
</map>