<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="../RDdzJRHnBLCEdVSLXLrGQGpDR4VqvugXDfhZQLeH7rBPaktPjdyNesqcSztt/mvdMfMJ4nhXj5vh8pd8AgqPf3d2fgTZsRkHTm6AJGpvVd7bX7ffRjpM9Y3uX/3MPEjDHjxamuMKwkVa7mzWP3nuNDLwKKgJqxZzavGbDMGeC2JX5kQLST9Dn9d.png" usemap="#image-map">

<map name="image-map">
    <area target="" alt="" title="" href="" coords="284,1626,286,1686,428,1686,463,1749,519,1771,569,1771,613,1749,642,1719,655,1689,793,1687,797,1624,655,1623,616,1562,575,1542,530,1537,456,1566,428,1621" shape="poly">
    <area target="" alt="" title="" href="" coords="300,1432,82,1275" shape="rect">
    <area target="" alt="" title="" href="" coords="311,1274,528,1432" shape="rect">
    <area target="" alt="" title="" href="" coords="549,1272,765,1430" shape="rect">
    <area target="" alt="" title="" href="" coords="784,1272,998,1428" shape="rect">
    <area target="" alt="" title="" href="" coords="84,1106,299,1263" shape="rect">
    <area target="" alt="" title="" href="" coords="312,1106,526,1260" shape="rect">
    <area target="" alt="" title="" href="" coords="547,1104,763,1264" shape="rect">
    <area target="" alt="" title="" href="" coords="784,1106,998,1260" shape="rect">
    <area target="" alt="" title="" href="" coords="85,940,297,1091" shape="rect">
    <area target="" alt="" title="" href="" coords="313,941,526,1091" shape="rect">
    <area target="" alt="" title="" href="" coords="548,936,763,1093" shape="rect">
    <area target="" alt="" title="" href="" coords="784,939,1000,1092" shape="rect">
    <area target="" alt="" title="" href="" coords="83,772,298,923" shape="rect">
    <area target="" alt="" title="" href="" coords="313,774,526,924" shape="rect">
    <area target="" alt="" title="" href="" coords="549,773,762,922" shape="rect">
    <area target="" alt="" title="" href="" coords="784,771,999,925" shape="rect">
    <area target="" alt="" title="" href="" coords="420,590,655,757" shape="rect">
</map>